In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('/content/SPAM text message 20170820 - Data.csv')
data

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
data.shape

(5572, 2)

In [ ]:
data.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [ ]:
data['spam'] = data['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [ ]:
data.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(data.Message, data.spam,test_size = 0.2)

In [ ]:
X_train.shape

(4457,)

In [ ]:
X_test.shape

(1115,)

In [ ]:
type(X_test)

pandas.core.series.Series

In [ ]:
y_train[:4]

2089    1
629     1
4235    0
2489    0
Name: spam, dtype: int64

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7736 sparse matrix of type '<class 'numpy.int64'>'
	with 59528 stored elements in Compressed Sparse Row format>

In [ ]:
X_train_cv.toarray()#2d multi-d array ayi

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_train_cv.shape

(4457, 7736)

In [ ]:
v.get_feature_names_out()[10:30]

array(['02072069400', '02073162414', '02085076972', '021', '03', '04',
       '0430', '05', '050703', '0578', '06', '07', '07008009200',
       '07046744435', '07090201529', '07090298926', '07099833605',
       '07123456789', '0721072', '07732584351'], dtype=object)

In [ ]:
v.get_feature_names_out().shape

(7736,)

In [ ]:
v.vocabulary_

{'well': 7452,
 'done': 2434,
 'england': 2614,
 'get': 3137,
 'the': 6817,
 'official': 4914,
 'poly': 5312,
 'ringtone': 5801,
 'or': 4987,
 'colour': 1932,
 'flag': 2911,
 'on': 4946,
 'yer': 7681,
 'mobile': 4561,
 'text': 6787,
 'tone': 6962,
 'to': 6936,
 '84199': 703,
 'now': 4854,
 'opt': 4981,
 'out': 5021,
 'txt': 7095,
 'eng': 2610,
 'stop': 6506,
 'box39822': 1495,
 'w111wx': 7330,
 '50': 558,
 'new': 4770,
 'textbuddy': 6791,
 'chat': 1776,
 'horny': 3514,
 'guys': 3304,
 'in': 3654,
 'ur': 7203,
 'area': 1082,
 'just': 3894,
 '25p': 389,
 'free': 3005,
 'receive': 5640,
 'search': 5979,
 'postcode': 5349,
 'at': 1146,
 'gaytextbuddy': 3111,
 'com': 1935,
 'one': 4952,
 'name': 4702,
 '89693': 744,
 'only': 4958,
 'reached': 5610,
 'home': 3489,
 'am': 965,
 'very': 7270,
 'tired': 6910,
 'will': 7515,
 'come': 1941,
 'tomorro': 6959,
 'aiyah': 919,
 'rain': 5567,
 'like': 4132,
 'quite': 5550,
 'big': 1379,
 'leh': 4096,
 'if': 3612,
 'drizzling': 2479,
 'can': 1663,
 'le

In [ ]:
v.get_feature_names_out()[7452]

'well'

In [ ]:
X_train_np = X_train_cv.toarray()
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
np.where(X_train_np[0]!=0)

(array([ 558,  703, 1495, 1932, 2434, 2610, 2614, 2911, 3137, 4561, 4854,
        4914, 4946, 4981, 4987, 5021, 5312, 5801, 6506, 6787, 6817, 6936,
        6962, 7095, 7330, 7452, 7681]),)

In [ ]:
X_train[:4][2089]

'Well done ENGLAND! Get the official poly ringtone or colour flag on yer mobile! text TONE or FLAG to 84199 NOW! Opt-out txt ENG STOP. Box39822 W111WX £1.50'

In [ ]:
X_train_np[0][7452]

1

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [ ]:
X_test_cv = v.transform(X_test)

In [ ]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)
print(classification_report(y_test,y_pred))#class was imbalanced so we used claasification_report

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       978
           1       1.00      0.91      0.95       137

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [ ]:
e = ['Hey sona, can we watch movie?',
     'upto 20% off on parking, exclusive offer for you. Dont miss this reward']
e_count = v.transform(e)
model.predict(e_count)

array([0, 1])

In [ ]:
#using pipeline
from sklearn.pipeline import Pipeline
clf = Pipeline([('vectorizer',CountVectorizer()),('nb',MultinomialNB())])

In [ ]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [ ]:
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       978
           1       1.00      0.91      0.95       137

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115

